const NAME_MAP: Record<string, string> = {
  // English → Spanish (football-data.org uses English)
  "Mexico": "México",
  "South Korea": "Corea del Sur",
  "Korea Republic": "Corea del Sur",
  "Czech Republic": "Chequia",
  "Czechia": "Chequia",
  "USA": "USA",
  "United States": "USA",
  "Turkey": "Türkiye",
  "Turkiye": "Türkiye",
  "Ivory Coast": "Costa de Marfil",
  "Côte d'Ivoire": "Costa de Marfil",
  "Cote d'Ivoire": "Costa de Marfil",
  "Netherlands": "Países Bajos",
  "Belgium": "Bélgica",
  "Germany": "Alemania",
  "France": "Francia",
  "Spain": "España",
  "Portugal": "Portugal",
  "England": "Inglaterra",
  "Argentina": "Argentina",
  "Brazil": "Brasil",
  "Morocco": "Marruecos",
  "Norway": "Noruega",
  "Sweden": "Suecia",
  "Switzerland": "Suiza",
  "Austria": "Austria",
  "Croatia": "Croacia",
  "Scotland": "Escocia",
  "Algeria": "Argelia",
  "Saudi Arabia": "Arabia Saudita",
  "Cape Verde": "Cabo Verde",
  "Uruguay": "Uruguay",
  "Ecuador": "Ecuador",
  "Colombia": "Colombia",
  "Paraguay": "Paraguay",
  "Australia": "Australia",
  "Japan": "Japón",
  "Iran": "Irán",
  "Senegal": "Senegal",
  "Ghana": "Ghana",
  "Egypt": "Egipto",
  "Tunisia": "Túnez",
  "New Zealand": "Nueva Zelanda",
  "Bosnia and Herzegovina": "Bosnia",
  "Bosnia & Herzegovina": "Bosnia",
  "DR Congo": "RD Congo",
  "Democratic Republic of Congo": "RD Congo",
  "Uzbekistan": "Uzbekistán",
  "Jordan": "Jordania",
  "Iraq": "Iraq",
  "Qatar": "Qatar",
  "Canada": "Canadá",
  "Haiti": "Haití",
  "Panama": "Panamá",
  "Curacao": "Curazao",
  "Curaçao": "Curazao",
  "South Africa": "Sudáfrica",
  "Serbia": "Serbia",
  // Already Spanish — pass through
  "México": "México",
  "Türkiye": "Türkiye",
  "Corea del Sur": "Corea del Sur",
  "Chequia": "Chequia",
  "Sudáfrica": "Sudáfrica",
  "Canadá": "Canadá",
  "Bosnia": "Bosnia",
  "Suiza": "Suiza",
  "Brasil": "Brasil",
  "Marruecos": "Marruecos",
  "Haití": "Haití",
  "Escocia": "Escocia",
  "Alemania": "Alemania",
  "Curazao": "Curazao",
  "Costa de Marfil": "Costa de Marfil",
  "Países Bajos": "Países Bajos",
  "Japón": "Japón",
  "Túnez": "Túnez",
  "Suecia": "Suecia",
  "Bélgica": "Bélgica",
  "Egipto": "Egipto",
  "Irán": "Irán",
  "Nueva Zelanda": "Nueva Zelanda",
  "España": "España",
  "Cabo Verde": "Cabo Verde",
  "Arabia Saudita": "Arabia Saudita",
  "Francia": "Francia",
  "Noruega": "Noruega",
  "Argelia": "Argelia",
  "Jordania": "Jordania",
  "RD Congo": "RD Congo",
  "Uzbekistán": "Uzbekistán",
  "Inglaterra": "Inglaterra",
  "Croacia": "Croacia",
  "Panamá": "Panamá",
  "C. de Marfil": "Costa de Marfil",
}

export function normalizeTeam(name: string): string {
  if (NAME_MAP[name]) return NAME_MAP[name]

  const lower = name.toLowerCase()
  for (const [key, val] of Object.entries(NAME_MAP)) {
    if (key.toLowerCase() === lower) return val
  }

  console.warn(`[normalize] Unknown team name: "${name}" — using as-is`)
  return name
}
